AllCops:
  Excludes:
    - db/**/*
    - config/**/*
    - script/**
    - spec/*_helper.rb
    - Gemfile
    - Rakefile
    - bin/**
Metrics/BlockLength:
  Exclude:
    - spec/**/*.rb

Documentation:
  Enabled: false

Style/FrozenStringLiteralComment:
  Enabled: false
