---
openapi: 3.0.1
info:
  title: API V1
  version: v1
paths:
  "/api/v1/login":
    post:
      summary: Sends verification code
      tags:
      - Login
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: data
        in: body
        required: true
        schema:
          type: object
          properties:
            email:
              type: string
            pair_nr:
              type: integer
          required:
          - email
          - pair_nr
          example:
            email: john@example.org
            pair_nr: 2
      responses:
        '200':
          description: Verification code was sent
        '401':
          description: Wrong credentials, verification code wasn't sent
          examples:
            application/json:
              error: Wrong credentials
        '503':
          description: |-
            Error with connection to external api occured,
                           verification code wasn't sent
          examples:
            application/json:
              error: Something went wrong
    patch:
      summary: Returns authentication token
      tags:
      - Login
      consumes:
      - application/json
      produces:
      - application/json
      parameters:
      - name: data
        in: body
        required: true
        schema:
          type: object
          properties:
            email:
              type: string
            verification_code:
              type: integer
          required:
          - email
          - pair_nr
          example:
            email: john@example.org
            verification_code: '123456'
      responses:
        '200':
          description: Verification code and emails are correct, token is returned
          examples:
            application/json:
              token: eyJhbGciOiJIUzI1NiJ9.eyJ1c2VyX2lkIjoxNTl9.pW9sdV1Vxrau3L-_33AvRF3zh_RdU_CWvGlDCT2Wf24
              user:
                id: 159
                first_name: first_name3
                last_name: last_name3
                email: john@example.org
                verified_login: false
                created_at: '2020-02-15T03:22:04.259Z'
                updated_at: '2020-02-15T03:22:04.259Z'
                phone: '613697109'
                city: Kraków
                pair_id: 80
        '401':
          description: |-
            Verification code and emails are incorrect,
                           error is returned
          examples:
            application/json:
              error: No user matching credentials
